spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usedTrade?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 0510

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#jwt:
#  secret: "asdklhfaskdjfljkasaslkmndasfkjbhfadskjhwertaoihewropijafsdhiuasfdgyhiuasdfuhbdfasuhdsafugvdfsagvydfsa1286423uiy5t873279ewqyfhadsbf8y23y498123u40qwhjifhbsdjfhjaksljf"
#  access_expiration: 100000
#  refresh_expiration: 100000

logging:
  level:
    org.hibernate.SQL: debug
